import Head from "next/head";
import Image from "next/image";
import Hero from "../components/hero";
import data from "../data/pages";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Monika Patel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {data &&
          data
            .sort(({ order: a }, { order: b }) => a - b)
            .map((box) => <Hero content={box} />)}
      </main>
    </div>
  );
}
