import Head from "next/head";
import Image from "next/image";
import Hero from "../components/hero";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Monika Patel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Hero content='About me' theme="Red" />
        <Hero content='Work 3' theme="Blue" />
        <Hero content='Work 2' theme="Green" />
        <Hero content='Work 1' theme="Yellow" />
        <Hero content='Education' theme="Violate" />
        
      </main>
    </div>
  );
}
